export const APP_LIMITS = {
  MAX_FILE_SIZE_GB: 5,
  MAX_FILE_SIZE_BYTES: 5 * 1024 * 1024 * 1024,
  MAX_DURATION_MINUTES: 600, // 10 hours
  SUPPORTED_FORMATS: ['MP3', 'WAV', 'M4A', 'FLAC', 'OGG', 'MP4', 'MOV'],
  AES_ENCRYPTION: 'AES-256-GCM',
  DIARIZATION_MAX_SPEAKERS: 12
};
